kind: pipeline
type: docker
name: default
trigger:
  branch:
    only:
      - master
      - gjq
    exclude:
      - idm410
  path:
    include:
      - build.gradle
steps:
  - name: build
    image: gradle:7.4
    volumes:
      - name: sdk
        path: /drone/src/sdk
      - name: gradle-cache
        path: /home/gradle/.gradle
    environment:
      ANDROID_HOME: /drone/src/sdk
    commands:
      - echo ${DRONE_SOURCE_BRANCH}
      - chmod +x gradlew
      - ./gradlew assembleDebug --stacktrace
#      - ./gradlew assemble --stacktrace
  - name: upload
    image: minio/mc:RELEASE.2024-01-16T16-06-34Z
    environment:
      ADDRESS:
        from_secret: MINIO_ADDRESS
      ACCESS_KEY:
        from_secret: MINIO_ACCESS_KEY
      SECRET_KEY:
        from_secret: MINIO_SECRET_KEY
    commands:
      - VERSION_NAME=$(grep "versionName" version.properties | cut -d'=' -f2)
      - VERSION_CODE=$(grep "versionCode" version.properties | cut -d'=' -f2)
      - echo $VERSION_NAME
      - echo $VERSION_CODE
      - mc config host add mio $ADDRESS $ACCESS_KEY $SECRET_KEY
      # 判断分支名称，根据不同的分支名称选择不同的目录
      - mc ls mio/uchi/AIDL/$VERSION_NAME
      - mc stat mio/uchi/AIDL/$VERSION_NAME > /dev/null 2>&1 || mc mb mio/uchi/AIDL/$VERSION_NAME
      - mc cp app/build/outputs/apk/id180_Csn_SuperLead_/debug/*.apk mio/uchi/AIDL/$VERSION_NAME
      - mc cp app/build/outputs/apk/id180_Tsc310e_SuperLead_/debug/*.apk mio/uchi/AIDL/$VERSION_NAME
      - mc cp app/build/outputs/apk/idm40_Csn_SuperLead_/debug/*.apk mio/uchi/AIDL/$VERSION_NAME
      - mc cp app/build/outputs/apk/idm40_Tsc310e_SuperLead_/debug/*.apk mio/uchi/AIDL/$VERSION_NAME

volumes:
  - name: sdk
    host:
      path: /mnt/user/appdata/drone/tools/android/sdk
  - name: gradle-cache
    host:
      path: /mnt/user/appdata/drone/tools/gradle/cache-icbc-aidl